# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45ef89245c94afb27785bf2b212b95514346a0466b4b187b90e6832dedeac934a4decaaa0b7415c580b4a6e20dbb7085701d6cc4ae54ffc40b4022491a4aaf8d

test:
  secret_key_base: ad265b5618aca4048d46d4e5e2a9ac76c43adceba5cfc039712c348dc58589154765bead0152d33be4ca37e426d2c4c01acf24cf047eb3c644e8abc346b5bc61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
